package com.college.guide;
import com.sun.net.httpserver.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.sql.*; import java.util.*;

public class App {
 static final Map<String,Session> sessions=new HashMap<>(); record Session(int id,String name,String role){}
 public static void main(String[] a)throws Exception { HttpServer s=HttpServer.create(new InetSocketAddress(8080),0); s.createContext("/",App::handle); s.setExecutor(null); s.start(); System.out.println("Guide Allocation System: http://localhost:8080"); }
 static void handle(HttpExchange x)throws IOException { try { String p=x.getRequestURI().getPath(); if(p.equals("/")||p.equals("/index.html")){send(x,200,"text/html",page());return;} if(p.equals("/app.js")){send(x,200,"application/javascript",js());return;} if(p.startsWith("/api/")){api(x,p);return;} send(x,404,"text/plain","Not found"); }catch(Exception e){e.printStackTrace();send(x,500,"application/json","{\"error\":\""+esc(e.getMessage())+"\"}");} }
 static void api(HttpExchange x,String p)throws Exception { Map<String,String>b=form(x); Session me=session(x); if(p.equals("/api/login")){try(Connection c=Database.get();PreparedStatement q=c.prepareStatement("SELECT id,name,role FROM users WHERE email=? AND password_hash=crypt(?, password_hash)")){q.setString(1,b.get("email"));q.setString(2,b.get("password"));ResultSet r=q.executeQuery();if(!r.next())throw new Exception("Invalid email or password");String t=UUID.randomUUID().toString();sessions.put(t,new Session(r.getInt(1),r.getString(2),r.getString(3)));x.getResponseHeaders().add("Set-Cookie","sid="+t+"; Path=/; HttpOnly");json(x,"{\"name\":\""+esc(r.getString(2))+"\",\"role\":\""+r.getString(3)+"\"}");}return;} if(p.equals("/api/logout")){sessions.remove(cookie(x));json(x,"{}");return;} if(me==null)throw new Exception("Please log in");
  if(p.equals("/api/me")){json(x,"{\"name\":\""+esc(me.name)+"\",\"role\":\""+me.role+"\"}");return;}
  if(p.equals("/api/faculty")){json(x,rows("SELECT f.faculty_id id,u.name,f.department,f.max_students,f.current_students,(f.max_students-f.current_students) seats_left,string_agg(d.domain_name, ', ') domains FROM faculty f JOIN users u ON u.id=f.faculty_id LEFT JOIN faculty_domains fd ON fd.faculty_id=f.faculty_id LEFT JOIN domains d ON d.domain_id=fd.domain_id GROUP BY f.faculty_id,u.name,f.department,f.max_students,f.current_students"));return;}
  if(p.equals("/api/domains")){json(x,rows("SELECT domain_id id,domain_name name FROM domains"));return;}
  if(p.equals("/api/announcements")){json(x,rows("SELECT a.announcement_id id,a.title,a.body,a.created_at,u.name author FROM announcements a JOIN users u ON u.id=a.author_id ORDER BY a.created_at DESC"));return;}
  if(p.equals("/api/request")&&me.role.equals("STUDENT")){exec("INSERT INTO guide_requests(student_id,faculty_id,domain_id) VALUES(?,?,?)",me.id,Integer.parseInt(b.get("facultyId")),Integer.parseInt(b.get("domainId")));json(x,"{\"message\":\"Request submitted\"}");return;}
  if(p.equals("/api/my-requests")&&me.role.equals("STUDENT")){json(x,rows("SELECT r.request_id id,u.name faculty,d.domain_name domain,r.status,r.request_date date FROM guide_requests r JOIN users u ON u.id=r.faculty_id JOIN domains d ON d.domain_id=r.domain_id WHERE r.student_id="+me.id+" ORDER BY r.request_date DESC"));return;}
  if(p.equals("/api/incoming")&&me.role.equals("FACULTY")){json(x,rows("SELECT r.request_id id,u.name student,s.registration_no,d.domain_name domain,r.status,r.request_date date FROM guide_requests r JOIN users u ON u.id=r.student_id JOIN students s ON s.student_id=r.student_id JOIN domains d ON d.domain_id=r.domain_id WHERE r.faculty_id="+me.id+" ORDER BY r.request_date DESC"));return;}
  if(p.equals("/api/decision")&&me.role.equals("FACULTY")){String status=b.get("status");if(status.equals("ACCEPTED")){try(Connection c=Database.get();CallableStatement q=c.prepareCall("CALL accept_guide_request(?,?)")){q.setInt(1,Integer.parseInt(b.get("requestId")));q.setInt(2,me.id);q.execute();}}else exec("UPDATE guide_requests SET status='REJECTED' WHERE request_id=? AND faculty_id=? AND status='PENDING'",Integer.parseInt(b.get("requestId")),me.id);json(x,"{\"message\":\"Request updated\"}");return;}
  if(p.equals("/api/projects")){String where=me.role.equals("STUDENT")?"p.student_id="+me.id:me.role.equals("FACULTY")?"p.faculty_id="+me.id:"1=1";json(x,rows("SELECT p.project_id id,p.title,p.description,p.status,su.name student,fu.name faculty,d.domain_name domain FROM projects p JOIN users su ON su.id=p.student_id JOIN users fu ON fu.id=p.faculty_id JOIN domains d ON d.domain_id=p.domain_id WHERE "+where));return;}
  if(p.equals("/api/milestone")&&me.role.equals("STUDENT")){exec("INSERT INTO milestones(project_id,title) SELECT project_id,? FROM projects WHERE student_id=?",b.get("title"),me.id);json(x,"{\"message\":\"Milestone submitted\"}");return;}
  if(p.equals("/api/announcement")&&(me.role.equals("ADMIN")||me.role.equals("FACULTY"))){exec("INSERT INTO announcements(author_id,title,body) VALUES(?,?,?)",me.id,b.get("title"),b.get("body"));json(x,"{\"message\":\"Announcement posted\"}");return;}
  if(p.equals("/api/admin/user")&&me.role.equals("ADMIN")){String role=b.get("role");int id;try(Connection c=Database.get();PreparedStatement q=c.prepareStatement("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,crypt(?,gen_salt('bf')),?) RETURNING id")){q.setString(1,b.get("name"));q.setString(2,b.get("email"));q.setString(3,b.get("password"));q.setString(4,role);ResultSet k=q.executeQuery();k.next();id=k.getInt(1);} if(role.equals("FACULTY"))exec("INSERT INTO faculty(faculty_id,department,max_students) VALUES(?,?,?)",id,b.get("department"),Integer.parseInt(b.get("capacity"))); else if(role.equals("STUDENT"))exec("INSERT INTO students(student_id,registration_no,department,semester) VALUES(?,?,?,?)",id,b.get("registration"),b.get("department"),Integer.parseInt(b.get("semester")));json(x,"{\"message\":\"User created\"}");return;}
  if(p.equals("/api/admin/domain")&&me.role.equals("ADMIN")){exec("INSERT INTO faculty_domains(faculty_id,domain_id) VALUES(?,?) ON CONFLICT DO NOTHING",Integer.parseInt(b.get("facultyId")),Integer.parseInt(b.get("domainId")));json(x,"{\"message\":\"Domain assigned\"}");return;}
  if(p.equals("/api/admin/lock")&&me.role.equals("ADMIN")){exec("UPDATE system_settings SET setting_value=? WHERE setting_key='allocations_locked'",b.get("locked"));json(x,"{\"message\":\"Allocation setting updated\"}");return;}
  if(p.equals("/api/report")&&me.role.equals("ADMIN")){json(x,rows("SELECT * FROM allocation_report"));return;} throw new Exception("Not authorized"); }
 static void exec(String sql,Object...v)throws Exception{try(Connection c=Database.get();PreparedStatement q=c.prepareStatement(sql)){for(int i=0;i<v.length;i++)q.setObject(i+1,v[i]);q.executeUpdate();}}
 static String rows(String sql)throws Exception{try(Connection c=Database.get();Statement q=c.createStatement();ResultSet r=q.executeQuery(sql)){StringBuilder o=new StringBuilder("[");ResultSetMetaData m=r.getMetaData();while(r.next()){if(o.length()>1)o.append(',');o.append('{');for(int i=1;i<=m.getColumnCount();i++){if(i>1)o.append(',');o.append('\"').append(m.getColumnLabel(i)).append("\":\"").append(esc(String.valueOf(r.getObject(i)))).append('\"');}o.append('}');}return o.append(']').toString();}}
 static Map<String,String> form(HttpExchange x)throws IOException{Map<String,String>m=new HashMap<>();String z=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);for(String e:z.split("&")){String[]a=e.split("=",2);if(a.length==2)m.put(URLDecoder.decode(a[0],"UTF-8"),URLDecoder.decode(a[1],"UTF-8"));}return m;}
 static String cookie(HttpExchange x){String c=x.getRequestHeaders().getFirst("Cookie");return c==null?"":Arrays.stream(c.split("; *")).filter(v->v.startsWith("sid=")).map(v->v.substring(4)).findFirst().orElse("");} static Session session(HttpExchange x){return sessions.get(cookie(x));} static String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ");} static void json(HttpExchange x,String s)throws IOException{send(x,200,"application/json",s);} static void send(HttpExchange x,int c,String t,String s)throws IOException{byte[]d=s.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type",t+"; charset=utf-8");x.sendResponseHeaders(c,d.length);x.getResponseBody().write(d);x.close();}
 static String page(){return """
<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><title>GuideFlow</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font:15px Arial}header{background:#192b50;color:white;padding:18px 8%;display:flex;justify-content:space-between}main{max-width:1050px;margin:28px auto;padding:0 18px}.card{background:#fff;border-radius:10px;padding:20px;margin:14px 0;box-shadow:0 2px 12px #1d2d4d16}input,select,textarea,button{padding:10px;margin:5px;border:1px solid #ccd4e0;border-radius:6px}button{background:#2463b5;color:#fff;border:0;cursor:pointer}button.danger{background:#b53131}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.item{border-left:4px solid #346fbd;padding:10px;background:#fafcff}.tag{font-size:12px;background:#e2edff;padding:4px 8px;border-radius:20px}h1,h2,h3{margin-top:0}.muted{color:#64748b}#toast{position:fixed;bottom:20px;right:20px;background:#172033;color:white;padding:12px;border-radius:6px;display:none}</style></head><body><header><b>GuideFlow</b><span id='user'></span></header><main id='app'></main><div id='toast'></div><script src='/app.js'></script></body></html>""";}
 static String js(){return """
const app=document.querySelector('#app'), user=document.querySelector('#user');
const api=async(p,d)=>{let r=await fetch(p,{method:d?'POST':'GET',headers:d?{'Content-Type':'application/x-www-form-urlencoded'}:{},body:d?new URLSearchParams(d):undefined});let x=await r.json();if(!r.ok)throw Error(x.error);return x};
const note=x=>{let n=document.querySelector('#toast');n.textContent=x;n.style.display='block';setTimeout(()=>n.style.display='none',2500)};
const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])); const cards=(a,f)=>a.length?a.map(f).join(''):'<p class=muted>No records yet.</p>';
async function login(){app.innerHTML=`<section class='card' style='max-width:430px;margin:70px auto'><h1>Welcome to GuideFlow</h1><p class=muted>Faculty guide allocation and project management.</p><form id=l><input required name=email type=email placeholder='Email' style='width:100%'><input required name=password type=password placeholder='Password' style='width:100%'><button style='width:100%'>Sign in</button></form><p class=muted>Demo password for all accounts: password</p></section>`;l.onsubmit=async e=>{e.preventDefault();try{await api('/api/login',Object.fromEntries(new FormData(l)));home()}catch(x){note(x.message)}}}
async function home(){let me=await api('/api/me');user.innerHTML=`${esc(me.name)} · ${me.role} <button id=out>Logout</button>`;out.onclick=async()=>{await api('/api/logout',{});login()};if(me.role==='STUDENT')student();else if(me.role==='FACULTY')faculty();else admin()}
async function student(){let [fs,ds,rs,ps,as]=await Promise.all([api('/api/faculty'),api('/api/domains'),api('/api/my-requests'),api('/api/projects'),api('/api/announcements')]);app.innerHTML=`<h1>Student dashboard</h1><div class=grid><section class=card><h2>Request a guide</h2><form id=req><select name=facultyId>${fs.filter(f=>f.seats_left>0).map(f=>`<option value=${f.id}>${esc(f.name)} (${f.seats_left} seats)</option>`)}</select><select name=domainId>${ds.map(d=>`<option value=${d.id}>${esc(d.name)}</option>`)}</select><button>Submit request</button></form></section><section class=card><h2>Submit milestone</h2><form id=mil><input name=title required placeholder='Milestone title'><button>Submit</button></form></section></div><section class=card><h2>Available faculty</h2><div class=grid>${cards(fs,f=>`<div class=item><b>${esc(f.name)}</b><br>${esc(f.department)} · <span class=tag>${f.seats_left} seats left</span><p>${esc(f.domains)}</p></div>`)}</div></section><section class=card><h2>My requests</h2>${cards(rs,r=>`<div class=item>${esc(r.faculty)} — ${esc(r.domain)} <b>${r.status}</b></div>`)}</section><section class=card><h2>My project</h2>${cards(ps,p=>`<div class=item><b>${esc(p.title)}</b> · ${p.status}<br>${esc(p.faculty)} / ${esc(p.domain)}</div>`)}</section>${ann(as)}`;req.onsubmit=post('/api/request',req,student);mil.onsubmit=post('/api/milestone',mil,student)}
async function faculty(){let [r,p,a]=await Promise.all([api('/api/incoming'),api('/api/projects'),api('/api/announcements')]);app.innerHTML=`<h1>Faculty dashboard</h1><section class=card><h2>Incoming guide requests</h2>${cards(r,x=>`<div class=item><b>${esc(x.student)}</b> (${esc(x.registration_no)}) · ${esc(x.domain)} · <b>${x.status}</b>${x.status==='PENDING'?` <button onclick="decision(${x.id},'ACCEPTED')">Accept</button><button class=danger onclick="decision(${x.id},'REJECTED')">Reject</button>`:''}</div>`)}</section><section class=card><h2>Supervised projects</h2>${cards(p,x=>`<div class=item><b>${esc(x.title)}</b> — ${esc(x.student)} · ${x.status}</div>`)}</section><section class=card><h2>Post announcement</h2><form id=post><input name=title required placeholder=Title><textarea name=body required placeholder=Message></textarea><button>Post</button></form></section>${ann(a)}`;post.onsubmit=post('/api/announcement',post,faculty)}
async function admin(){let [rep,fs,ds,a]=await Promise.all([api('/api/report'),api('/api/faculty'),api('/api/domains'),api('/api/announcements')]);app.innerHTML=`<h1>Coordinator dashboard</h1><div class=grid><section class=card><h2>Add user</h2><form id=add><input name=name required placeholder=Name><input name=email required type=email placeholder=Email><input name=password required placeholder='Temporary password'><select name=role><option>STUDENT</option><option>FACULTY</option></select><input name=department required placeholder=Department><input name=registration placeholder='Registration no. (student)'><input name=semester type=number value=1 placeholder='Semester'><input name=capacity type=number value=5 placeholder='Capacity'><button>Create user</button></form></section><section class=card><h2>Assign faculty domain</h2><form id=assign><select name=facultyId>${fs.map(x=>`<option value=${x.id}>${esc(x.name)}</option>`)}</select><select name=domainId>${ds.map(x=>`<option value=${x.id}>${esc(x.name)}</option>`)}</select><button>Assign</button></form><h2>Allocation lock</h2><button id=lock>Lock new requests</button><button id=unlock>Unlock requests</button></section></div><section class=card><h2>Allocation report</h2>${cards(rep,x=>`<div class=item><b>${esc(x.faculty)}</b> — ${x.allocated_students} allocated student(s)</div>`)}</section><section class=card><h2>Faculty capacity</h2>${cards(fs,x=>`<div class=item><b>${esc(x.name)}</b> — ${x.current_students}/${x.max_students} allocated</div>`)}</section><section class=card><h2>Post announcement</h2><form id=post><input name=title required placeholder=Title><textarea name=body required placeholder=Message></textarea><button>Post</button></form></section>${ann(a)}`;post.onsubmit=post('/api/announcement',post,admin);add.onsubmit=post('/api/admin/user',add,admin);assign.onsubmit=post('/api/admin/domain',assign,admin);lock.onclick=()=>api('/api/admin/lock',{locked:'true'}).then(x=>{note(x.message);admin()});unlock.onclick=()=>api('/api/admin/lock',{locked:'false'}).then(x=>{note(x.message);admin()})}
function ann(a){return `<section class=card><h2>Announcements</h2>${cards(a,x=>`<div class=item><b>${esc(x.title)}</b><p>${esc(x.body)}</p><small>${esc(x.author)} · ${esc(x.created_at)}</small></div>`)}</section>`};function post(url,f,next){return async e=>{e.preventDefault();try{let x=await api(url,Object.fromEntries(new FormData(f)));note(x.message);next()}catch(x){note(x.message)}}};window.decision=async(id,status)=>{try{note((await api('/api/decision',{requestId:id,status})).message);faculty()}catch(x){note(x.message)}};home().catch(login);
""";}
}
