-- Run this file after creating a database named faculty_guide_db in pgAdmin.
-- It is written for PostgreSQL 14+.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(10) NOT NULL CHECK (role IN ('STUDENT','FACULTY','ADMIN')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE students (
  student_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  registration_no VARCHAR(30) NOT NULL UNIQUE, department VARCHAR(80) NOT NULL,
  semester INTEGER NOT NULL CHECK (semester > 0)
);
CREATE TABLE faculty (
  faculty_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  department VARCHAR(80) NOT NULL, max_students INTEGER NOT NULL DEFAULT 5 CHECK (max_students >= 0),
  current_students INTEGER NOT NULL DEFAULT 0 CHECK (current_students >= 0 AND current_students <= max_students)
);
CREATE TABLE domains (domain_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, domain_name VARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE faculty_domains (
  faculty_id INTEGER NOT NULL REFERENCES faculty(faculty_id) ON DELETE CASCADE,
  domain_id INTEGER NOT NULL REFERENCES domains(domain_id) ON DELETE CASCADE, PRIMARY KEY (faculty_id, domain_id)
);
CREATE TABLE guide_requests (
  request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(student_id), faculty_id INTEGER NOT NULL REFERENCES faculty(faculty_id),
  domain_id INTEGER NOT NULL REFERENCES domains(domain_id), request_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACCEPTED','REJECTED')),
  UNIQUE (student_id, faculty_id, domain_id)
);
CREATE TABLE projects (
  project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL DEFAULT 'Untitled Project', description TEXT,
  student_id INTEGER NOT NULL UNIQUE REFERENCES students(student_id), faculty_id INTEGER NOT NULL REFERENCES faculty(faculty_id),
  domain_id INTEGER NOT NULL REFERENCES domains(domain_id),
  status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','COMPLETED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE milestones (
  milestone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
  title VARCHAR(150) NOT NULL, submission_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','REVIEWED','REVISION_REQUIRED')), faculty_remark TEXT
);
CREATE TABLE announcements (
  announcement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, author_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(150) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE system_settings (setting_key VARCHAR(50) PRIMARY KEY, setting_value BOOLEAN NOT NULL);
INSERT INTO system_settings VALUES ('allocations_locked', FALSE);

CREATE OR REPLACE FUNCTION validate_request() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM system_settings WHERE setting_key='allocations_locked' AND setting_value) THEN RAISE EXCEPTION 'Guide allocations are locked by the coordinator'; END IF;
  IF EXISTS (SELECT 1 FROM projects WHERE student_id=NEW.student_id) THEN RAISE EXCEPTION 'Student already has an approved guide'; END IF;
  IF EXISTS (SELECT 1 FROM faculty WHERE faculty_id=NEW.faculty_id AND current_students >= max_students) THEN RAISE EXCEPTION 'Faculty capacity is full'; END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER validate_request_before_insert BEFORE INSERT ON guide_requests FOR EACH ROW EXECUTE FUNCTION validate_request();

CREATE OR REPLACE FUNCTION create_project_after_accept() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status='ACCEPTED' AND OLD.status <> 'ACCEPTED' THEN
    INSERT INTO projects(student_id,faculty_id,domain_id) VALUES(NEW.student_id,NEW.faculty_id,NEW.domain_id);
    UPDATE faculty SET current_students=current_students+1 WHERE faculty_id=NEW.faculty_id;
    UPDATE guide_requests SET status='REJECTED' WHERE student_id=NEW.student_id AND request_id<>NEW.request_id AND status='PENDING';
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER create_project_after_accept AFTER UPDATE ON guide_requests FOR EACH ROW EXECUTE FUNCTION create_project_after_accept();

-- The faculty row lock prevents simultaneous approvals from exceeding capacity.
CREATE OR REPLACE PROCEDURE accept_guide_request(p_request_id INTEGER, p_faculty_id INTEGER) LANGUAGE plpgsql AS $$
DECLARE request_row guide_requests%ROWTYPE;
BEGIN
  SELECT * INTO request_row FROM guide_requests WHERE request_id=p_request_id AND faculty_id=p_faculty_id AND status='PENDING' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Request is unavailable'; END IF;
  PERFORM 1 FROM faculty WHERE faculty_id=p_faculty_id AND current_students < max_students FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Faculty capacity is full'; END IF;
  IF EXISTS (SELECT 1 FROM projects WHERE student_id=request_row.student_id) THEN RAISE EXCEPTION 'Student already has an approved guide'; END IF;
  UPDATE guide_requests SET status='ACCEPTED' WHERE request_id=p_request_id;
END; $$;

CREATE VIEW faculty_availability AS SELECT f.faculty_id,u.name,u.email,f.department,f.max_students,f.current_students,(f.max_students-f.current_students) seats_left FROM faculty f JOIN users u ON u.id=f.faculty_id;
CREATE VIEW allocation_report AS SELECT u.name faculty,COUNT(p.project_id) allocated_students FROM faculty f JOIN users u ON u.id=f.faculty_id LEFT JOIN projects p ON p.faculty_id=f.faculty_id GROUP BY f.faculty_id,u.name;

INSERT INTO domains(domain_name) VALUES ('Artificial Intelligence'),('Machine Learning'),('Blockchain'),('Data Science'),('Cyber Security'),('Cloud Computing'),('IoT');
INSERT INTO users(id,name,email,password_hash,role) VALUES
  (1,'Aarav Student','student1@college.edu',crypt('password',gen_salt('bf')),'STUDENT'),
  (2,'Dr. Priya Sharma','faculty1@college.edu',crypt('password',gen_salt('bf')),'FACULTY'),
  (3,'Department Coordinator','admin@college.edu',crypt('password',gen_salt('bf')),'ADMIN');
INSERT INTO students(student_id,registration_no,department,semester) VALUES(1,'23BCE1001','Computer Science',5);
INSERT INTO faculty(faculty_id,department,max_students) VALUES(2,'Computer Science',4);
INSERT INTO faculty_domains(faculty_id,domain_id) VALUES(2,1),(2,2),(2,4);
SELECT setval(pg_get_serial_sequence('users','id'),(SELECT MAX(id) FROM users));
